# -*- coding: utf-8 -*-
"""DAA-P1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LQisPRXhCrsfFAR94YMw76E_RQBn1CN7
"""

x = int(input("Bilangan 1 = "))
y = int(input("Bilangan 2 = "))

if x > y:
  print("Bilangan terbesar adalah ",x)
elif y > x:
  print("Bilangan terbesar adalah ",y)
else:
  print("Bilangan terbesar adalah ",x)